### ISSUE TITLE
[meta] ideas

### ISSUE THREAD

**Issue by jordens** [quartiq/thermostat#1]
* [ ] **CM** use proper IIR filter, parameter calculation (c.f. Stabilizer, derivative-kick, anti-windup, smooth behavior on I gain change)
* [ ] **C+** safety features (sensor open, interlock, bad TEC behavior)
* [ ] **C+** rtfm
* [ ] **C++** mqtt (c.f. Stabilizer, Booster)
* [ ] **C** dhcp
* [ ] **C+** persistent settings
* [ ] **CE** anti-windup when the PWM rails (V or I), not when the I DAC rails
* [ ] **EC+** thermal management (adaptive max power)
* [ ] **CE+** PoE compat (current/power max, AT_DET, maybe LLDP)
* [ ] **ECM+** transfer function measurement (log sweep or prng)
* [ ] **CM+** auto-tuning
* [ ] **EC+** characterize/tune/adjust bandwidth/accuracy trade-off (faster sampling at higher rate without line noise suppression for small thermal masses)
* [ ] **CE+** incorporate/learn external feed-forward (given known external heat source/sink and coupling) or "sensor mapping" (interpolation between two sensors)

**C**ode
**M**ath
**E**lectronics
**+** tricky
**++** very tricky
